identification: ''
locus:
- '1'
- '2'
- '3'
- '4'
- '5'
- '6'
- '7'
- '8'
project: test_flu_34
proteins:
- PB2
- PB1
- PA
- HA
- NP
- locus_00006
- NA
- M
- NS
sample_type:
  demo_MPXV_004: snippy
  demo_MPXV_005: snippy
  demo_MPXV_006: snippy
  demo_MPXV_007: snippy
  demo_MPXV_008: snippy
samples:
  demo_MPXV_004:
    fastq1: demo_MPXV_004_R1_001
    fastq2: demo_MPXV_004_R2_001
    tech: illumina
  demo_MPXV_005:
    fastq1: demo_MPXV_005_R1_001
    fastq2: demo_MPXV_005_R2_001
    tech: illumina
  demo_MPXV_006:
    fastq1: demo_MPXV_006_R1_001
    fastq2: demo_MPXV_006_R2_001
    tech: illumina
  demo_MPXV_007:
    fastq1: demo_MPXV_007_R1_001
    fastq2: demo_MPXV_007_R2_001
    tech: illumina
  demo_MPXV_008:
    fastq1: demo_MPXV_008_R1_001
    fastq2: demo_MPXV_008_R2_001
    tech: illumina
version: ''
