identification: ''
locus:
- '1'
- '2'
- '3'
- '4'
- '5'
- '6'
- '7'
- '8'
project: influenza_dataset
proteins:
- PB2
- PB1
- PA
- HA
- NP
- locus_00006
- NA
- M
- NS
sample_type:
  demo_influenza_01: snippy
  demo_influenza_02: snippy
  demo_influenza_03: snippy
samples:
  demo_influenza_01:
    fastq1: influenza_01_R1_001
    fastq2: influenza_01_R2_001
    tech: illumina
  demo_influenza_02:
    fastq1: influenza_02_R1_001
    fastq2: influenza_02_R2_001
    tech: illumina
  demo_influenza_03:
    fastq1: influenza_03_R1_001
    fastq2: influenza_03_R2_001
    tech: illumina
version: ''
