identification: ''
locus: Flu
project: flu_testing_BVictoria
proteins:
- PB2
- PB1
- PA
- HA
- NP
- NA
- M_1
- M_2
- NS
sample_type:
  ERR974981: medaka
  SRR10885405: snippy
  SRR10885406: snippy
samples:
- SRR10885405
- SRR10885406
- ERR974981
version: ''
