identification: MN908947
locus:
- SARS_CoV_2
project: sars_dataset
proteins:
- orf1ab
- S
- ORF3a
- E
- M
- ORF6
- ORF7a
- ORF8
- N
- ORF10
sample_type:
  demo_SARSCoV2_065: snippy
  demo_SARSCoV2_066: snippy
  demo_SARSCoV2_067: snippy
  demo_SARSCoV2_069: medaka
  demo_SARSCoV2_070: medaka
  demo_SARSCoV2_072: medaka
  demo_SARSCoV2_073: medaka
samples:
  demo_SARSCoV2_065:
    fastq1: Demo_Sample_065_R1_001
    fastq2: Demo_Sample_065_R2_001
    tech: illumina
  demo_SARSCoV2_066:
    fastq1: Demo_Sample_066_R1_001
    fastq2: Demo_Sample_066_R2_001
    tech: illumina
  demo_SARSCoV2_067:
    fastq1: Demo_Sample_067_R1_001
    fastq2: null
    tech: illumina
  demo_SARSCoV2_069:
    fastq1: Demo_Sample_069
    fastq2: null
    tech: ont
  demo_SARSCoV2_070:
    fastq1: Demo_Sample_070
    fastq2: null
    tech: ont
  demo_SARSCoV2_072:
    fastq1: Demo_Sample_072
    fastq2: null
    tech: ont
  demo_SARSCoV2_073:
    fastq1: Demo_Sample_073
    fastq2: null
    tech: ont
version: '3'
