identification: ''
locus: Flu
project: flu_iVar
proteins:
- PB2
- PB1
- PA
- HA
- NP
- NA
- M
- NS
sample_type:
  influenza_01: iVar
  influenza_02: iVar
  influenza_03: iVar
  influenza_04: iVar
samples:
  influenza_01:
    fastq1: influenza_01_R1_001
    fastq2: influenza_01_R2_001
    tech: illumina
  influenza_02:
    fastq1: influenza_02_R1_001
    fastq2: influenza_02_R2_001
    tech: illumina
  influenza_03:
    fastq1: influenza_03_R1_001
    fastq2: influenza_03_R2_001
    tech: illumina
  influenza_04:
    fastq1: influenza_04_R1_001
    fastq2: influenza_04_R2_001
    tech: illumina
version: ''
