identification: MN908947
locus: SARS_CoV_2
project: ont
proteins:
- orf1ab
- S
- ORF3a
- E
- M
- ORF6
- ORF7a
- ORF8
- N
- ORF10
sample_type:
  ERR974981: medaka
  SRR10885405: iVar
  SRR10885406: iVar
samples:
  ERR974981:
    fastq1: ERR974981
    fastq2: null
    tech: ont
  SRR10885405:
    fastq1: SRR10885405_1
    fastq2: SRR10885405_2
    tech: illumina
  SRR10885406:
    fastq1: SRR10885406_1
    fastq2: SRR10885406_2
    tech: illumina
version: '3'
