identification: MN908947
locus:
- SARS_CoV_2
project: test_ont_covid
proteins:
- orf1ab
- S
- ORF3a
- E
- M
- ORF6
- ORF7a
- ORF8
- N
- ORF10
sample_type:
  Demo_Sample_069: medaka
  Demo_Sample_070: medaka
  Demo_Sample_101: medaka
  Demo_Sample_102: medaka
  Demo_Sample_103: medaka
samples:
  Demo_Sample_069:
    fastq1: Demo_Sample_069
    fastq2: null
    tech: ont
  Demo_Sample_070:
    fastq1: Demo_Sample_070
    fastq2: null
    tech: ont
  Demo_Sample_101:
    fastq1: Demo_Sample_101
    fastq2: null
    tech: ont
  Demo_Sample_102:
    fastq1: Demo_Sample_102
    fastq2: null
    tech: ont
  Demo_Sample_103:
    fastq1: Demo_Sample_103
    fastq2: null
    tech: ont
version: '3'
