working: ../results/
user_metadata: ../user_metadata/
sample_yaml: ../user_metadata/sample_metadata.yaml
sample_csv: ../user_metadata/sample_metadata.csv
references: ../references/
rules: ../workflow/rules/
envs: ../envs/
scripts: ../workflow/scripts/
samples: ../user_data/
config_file: ../config/config.yaml
software_parameters: ../user_metadata/parameters.yaml
get_coverage: ../workflow/software/getCoverage/getCoverage.py
assembler: snippy #"iVar"
