working: ../results/
user_metadata: ../user_metadata/
sample_yaml: ../user/demo_SARS_CoV_2_INSaFLU.yaml
sample_csv: ../user/demo_SARS_CoV_2_INSaFLU.csv
references: ../user/references/
rules: ../workflow/rules/
envs: ../envs/
scripts: ../workflow/scripts/
samples: ../user/reads/
config_file: ../config/config.yaml
software_parameters: ../user/parameters.yaml
get_coverage: ../workflow/software/getCoverage/getCoverage.py
assembler: snippy #"iVar"
