working: ../results/
user_metadata: ../user_metadata/
sample_yaml: ../user/sars_cov_2.yaml #sample
sample_csv: ../user/sars_cov_2.csv #csv
config_file: ../config/config.yaml
software_parameters: ../user/parameters.yaml
get_coverage: ../workflow/software/getCoverage/getCoverage.py
references: ../user/references/
rules: ../workflow/rules/
envs: ../envs/
scripts: ../workflow/scripts/
samples: ../user/reads/
threads: ../config/threads.yaml
