freebayes: 522
prepare_snpeff: 306
snpeff: 800
snpeff_sample: 222
getCoverage: 116
point mergeCoverage: 28
makeproject: 68
assemble_consensus: 92
create_segments: 28
trimme_reads_PE: 1136
trimme_reads_SE: 1136
fasttree: 1924
fasttree_proteins: 188
fasttree_nt: 3676
cp_Alignment_nt_tree: 46
translate: 94
medaka_consensus: 4620
medaka_get_depth: 72
medaka_split_depth: 110
medaka_call_variants: 552
medaka_annotate_variants: 590
mask_between_top_and_50: 168
bcf_consensus: 74
create_align_file: 74
msa_masker_medaka: 150
get_masked_consensus_medaka: 74
mask_regions_consensus_medaka: 76
raw_nanostat: 396
trimmed_nanostat: 370
point abricate_pangolin: 114
not_pangolin: 6
pangolin: 834
seqret_all_nt: 6
seqret_all_nt_only_90: 10
seqret_all_consensus: 26
alignment_nt_All_seqret: 32
align_w_mafft_medaka: 142
align_mafft_snippy: 146
mafft_pre_aa: 1858
mafft: 1858
mafft_nt: 1860
mafft_proteins: 348
snippy_pe: 4134
snippy_se: 3794
primers_bam: 52
snippy_split_depth: 116
create_align_file_snippy: 76
msa_masker_snippy: 172
get_masked_consensus_snippy: 74
mask_regions_consensus_snippy: 76
nanofilt_SE: 142
raw_fastqc_se: 680
raw_fastqc_pe: 680
trimmed_fastqc_pe: 1264
trimmed_fastqc_se: 1264
iVar_align_pe: 1856
iVar_align_se: 1856
ivar_primers: 1656
call_variant: 2642
generate_consensus: 732
get_depth: 74
iVar_depth_1_2: 208
iVar_depth_step_2: 106
create_align_file_iVar: 76
align_mafft_iVar: 146
msa_masker_iVar: 124
get_masked_consensus_iVar: 74
mask_regions_consensus_iVar: 82
abricate_se: 156
abricate_pe: 156
abricate_ont: 156
variant_validated: 8
snpeff_concat: 26
snpeff_concat_indels: 78
proportions_iSNVs_graph: 24
spades_se: 5468
spades_pe: 5468
