freebayes: 500
prepare_snpeff: 500
snpeff: 800
snpeff_sample: 500
getCoverage: 500
mergeCoverage: 500
makeproject: 500
assemble_consensus: 500
create_segments: 500
trimme_reads_PE: 1136
trimme_reads_SE: 1136
fasttree: 1924
fasttree_proteins: 500
fasttree_nt: 3676
cp_Alignment_nt_tree: 500
translate: 500
medaka_consensus: 4620
medaka_get_depth: 500
medaka_split_depth: 500
medaka_call_variants: 552
medaka_annotate_variants: 590
mask_between_top_and_50: 168
bcf_consensus: 500
create_align_file: 500
msa_masker_medaka: 500
get_masked_consensus_medaka: 500
mask_regions_consensus_medaka: 500
raw_nanostat: 500
trimmed_nanostat: 500
point abricate_pangolin: 500
not_pangolin: 500
pangolin: 834
seqret_all_nt: 200
seqret_all_nt_only_90: 200
seqret_all_consensus: 200
alignment_nt_All_seqret: 200
align_w_mafft_medaka: 500
align_mafft_snippy: 500
mafft_pre_aa: 4000
mafft: 4000
mafft_nt: 4000
mafft_proteins: 3000
snippy_pe: 5000
snippy_se: 5000
primers_bam: 500
snippy_split_depth: 500
create_align_file_snippy: 500
msa_masker_snippy: 500
get_masked_consensus_snippy: 500
mask_regions_consensus_snippy: 500
nanofilt_SE: 500
raw_fastqc_se: 1000
raw_fastqc_pe: 1000
trimmed_fastqc_pe: 3000
trimmed_fastqc_se: 3000
iVar_align_pe: 3000
iVar_align_se: 3000
ivar_primers: 3000
call_variant: 4000
generate_consensus: 2000
get_depth: 500
iVar_depth_1_2: 500
iVar_depth_step_2: 500
create_align_file_iVar: 500
align_mafft_iVar: 500
msa_masker_iVar: 500
get_masked_consensus_iVar: 500
mask_regions_consensus_iVar: 500
abricate_se: 500
abricate_pe: 500
abricate_ont: 500
variant_validated: 500
snpeff_concat: 500
snpeff_concat_indels: 500
proportions_iSNVs_graph: 500
spades_se: 8000
spades_pe: 8000
get_vcf: 500
snippy_unzip_depth: 500
initiate_folder: 500
seqret_alignment_aa_gene: 500
alignment_nt_seg_mafft_seqret: 500
alignment_nt_seg_seqret: 500
alignment_nt_specific_seqret: 500
cp_Alignment_nt: 500
warning: 500
