only_samples: False
project_name: ont
locus: SARS_CoV_2 #MonkeyPox #Flu #SARS_CoV_2 # <= Case Sensitive # this the reference name in the fasta file!
fasta_reference: reference/SARS_CoV_2_COVID_19_Wuhan_Hu_1_MN908947.fasta #reference/A_H1N1pdm09_A_Michigan_45_2015.fasta  #reference/SARS_CoV_2_Wuhan_Hu_1_MN908947.fasta 
gb_reference: reference/SARS_CoV_2_COVID_19_Wuhan_Hu_1_MN908947.gb #reference/A_H1N1pdm09_A_Michigan_45_2015.gbk #reference/SARS_CoV_2_Wuhan_Hu_1_MN908947.gb  # 
