only_samples: False
project_name: flu_testing_BVictoria
locus: Flu 
fasta_reference: reference/B_Vic_B_Brisbane_60_2008.fasta  #reference/SARS_CoV_2_Wuhan_Hu_1_MN908947.fasta 
gb_reference: reference/B_Vic_B_Brisbane_60_2008.gbk #reference/SARS_CoV_2_Wuhan_Hu_1_MN908947.gb  # 
