only_samples: False
project_name: first_flu
locus: Flu #SARS_CoV_2 #MonkeyPox #Flu  <= Case Sensitive
fasta_reference: reference/A_H1N1pdm09_A_Michigan_45_2015.fasta
gb_reference: reference/A_H1N1pdm09_A_Michigan_45_2015.gbk
