min_coverage_consensus: 90

##ILLUMINA / Ion Torrent data##
# Trimmomatic 
ILLUMINACLIP: null #(default: Not apply)
HEADCROP: 0 #(default = 0)
CROP: 0 #(default = 0)
SLIDINGWINDOW1: 5 #(default = 5)
SLIDINGWINDOW2: 20 #(default = 20)
LEADING: 3 #(default = 3)
TRAILING: 3 #(default = 3)
MINLEN: 35 #(default = 35)

## Oxford Nanopore Technologies (ONT) data ##
# NanoFilt 
QUALITY: 10 #(default: 10)
LENGTH: 50 #(default: 50)
HEADCROP: 70 #(default: 70)
TAILCROP: 70 #(default: 70)
MAXLENGTH: 0 #(default: 0)


#Mapping, Variant Calling
##ILLUMINA / Ion Torrent data##

### Snippy

mapqual: 20 #(default = 20)

mincov: 10 #default = 10)

minfrac: 0.51 #(default = 0.51)

## Oxford Nanopore Technologies (ONT) data ##
## Medaka

Medaka_model: r941_min_high_g360 #(default: r941_min_high_g360) (see: https://nanoporetech.github.io/medaka/)

mincov_medaka: 30 #(default: 30)

Min_prop_for_variant_evidence: 0.8 #(default: 0.8).

# MASK ALL CONSENSUS IN PROJECT 
MASK_SITES: null #1,2,3,4
MASK_REGIONS: null #200-250
MASK_F_BEGINNING: null #40
MASK_F_END: null #100