only_samples: False
project_name: single_test
fasta_reference: SARS_CoV_2_Wuhan_Hu_1_MN908947.fasta
gb_reference: SARS_CoV_2_Wuhan_Hu_1_MN908947.gbk
abricate: False
illumina_consensus: iVar
primers_fasta: sars_cov_2_artic_4_1.fasta
