name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8
    
    - name: Install Snakemake and snakefmt
      shell: bash -l {0}
      run: |
        conda env create --name insaflu --file config/insaflu.yaml
        conda activate insaflu
        conda install -n insaflu -c bioconda snakefmt
    
    - name: Lint with snakefmt
      shell: bash -l {0}
      run: |
        conda activate insaflu
        snakefmt workflow/Snakefile workflow/rules

    - name: Execute Snakemake
      shell: bash -l {0}
      run: |
        conda activate insaflu
        snakemake --cores 1 --use-conda

    # New step to compare the generated files to expected outputs
    - name: Validate output files
      run: |
        # Compute checksums for the generated files
        sha256sum results/samples/demo_illumina_1/trimmed_reads/demo_illumina_1_1.trimmed.fastq.gz > generated_checksums.txt
        sha256sum results/samples/demo_illumina_1/trimmed_reads/demo_illumina_1_2.trimmed.fastq.gz >> generated_checksums.txt
        sha256sum results/samples/demo_ont_1/trimmed_reads/nano_demo_ont_1.trimmed.fastq.gz >> generated_checksums.txt
        diff generated_checksums.txt .test_expected/expected_checksums.txt
