name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches:
      - main
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.8
    
    - name: Install Snakemake and snakefmt
      shell: bash -l {0}
      run: |
        conda env create --name insaflu --file config/insaflu.yaml
        conda activate insaflu
        conda install -n base -c conda-forge mamba
        conda install -n insaflu -c bioconda snakefmt
    
    - name: Lint with snakefmt
      shell: bash -l {0}
      run: |
        conda activate insaflu
        snakefmt workflow/Snakefile workflow/rules

    - name: Execute Snakemake Snippy
      shell: bash -l {0}
      run: |
        conda activate insaflu
        snakemake --cores 1 --use-conda

        # New step to compare the generated files to expected outputs
    - name: Validate output files snippy
      run: |
        # Compute checksums for the generated files
        sha256sum results/samples/demo_ont_1/trimmed_reads/nano_demo_ont_1.trimmed.fastq.gz >> output_snippy.txt
        sha256sum results/samples/demo_illumina_1/trimmed_reads/demo_illumina_1_1.trimmed.fastq.gz >> output_snippy.txt
        sha256sum results/samples/demo_illumina_1/trimmed_reads/demo_illumina_1_2.trimmed.fastq.gz >> output_snippy.txt
        sha256sum results/align_samples/demo_illumina_1/snippy/demo_illumina_1_consensus.fasta >> output_snippy.txt
        sha256sum results/align_samples/demo_ont_1/medaka/demo_ont_1_consensus.fasta >> output_snippy.txt
        sha256sum results/projects/snippy_project/main_result/Alignment_nt_All.fasta >> output_snippy.txt
        sha256sum results/projects/snippy_project/main_result/coverage_translate.csv >> output_snippy.txt
        diff output_snippy.txt .test_expected/expected_snippy.txt

    - name: Execute Snakemake
      shell: bash -l {0}
      run: |
        sed s/snippy/iVar/g user/project.yaml > user/project.yaml
        conda activate insaflu
        snakemake --cores 1 --use-conda

    - name: Validate output files iVar
      run: |
        # Compute checksums for the generated files
        sha256sum results/samples/demo_ont_1/trimmed_reads/nano_demo_ont_1.trimmed.fastq.gz >> output_ivar.txt
        sha256sum results/samples/demo_illumina_1/trimmed_reads/demo_illumina_1_1.trimmed.fastq.gz >> output_ivar.txt
        sha256sum results/samples/demo_illumina_1/trimmed_reads/demo_illumina_1_2.trimmed.fastq.gz >> output_ivar.txt
        sha256sum results/align_samples/demo_illumina_1/iVar/demo_illumina_1_consensus.fasta >> output_ivar.txt
        sha256sum results/projects/iVar_project/main_result/coverage_translate.csv >> output_ivar.txt
        sha256sum results/projects/iVar_project/main_result/Alignment_nt_All.fasta >> output_ivar.txt

        diff output_ivar.txt .test_expected/expected_ivar.txt



